# Generated by Django 5.2.6 on 2025-09-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True, help_text="종목 코드", max_length=20
                    ),
                ),
                ("date", models.DateField(db_index=True, help_text="날짜")),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=2, help_text="시가", max_digits=12
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=2, help_text="고가", max_digits=12
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=2, help_text="저가", max_digits=12
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=2, help_text="종가", max_digits=12
                    ),
                ),
                ("volume", models.BigIntegerField(help_text="거래량")),
            ],
            options={
                "verbose_name": "과거 시세 데이터",
                "verbose_name_plural": "과거 시세 데이터",
                "ordering": ["-date"],
                "unique_together": {("symbol", "date")},
            },
        ),
    ]
