# Generated by Django 5.2.6 on 2025-09-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text="전략 실행에 필요한 파라미터 (e.g., {'short_ma': 5, 'long_ma': 20})"),
        ),
    ]
