# Generated by Django 5.2.6 on 2025-09-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_strategy_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='종목코드', max_length=20, unique=True)),
                ('stock_name', models.CharField(help_text='종목명', max_length=100)),
                ('is_investable', models.BooleanField(default=False, help_text='1차 분석(위험성) 통과 여부')),
                ('investment_horizon', models.CharField(choices=[('SHORT', '단기'), ('MID', '중기'), ('LONG', '장기'), ('NONE', '미분류')], default='NONE', help_text='2차 분석(투자 기간) 결과', max_length=5)),
                ('analysis_date', models.DateField(auto_now=True, help_text='분석이 수행된 날짜')),
                ('last_price', models.DecimalField(decimal_places=2, default=0, help_text='분석 시점의 현재가', max_digits=15)),
                ('raw_analysis_data', models.JSONField(blank=True, default=dict, help_text='분석에 사용된 원본 데이터, 지표 등')),
            ],
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='order_id',
            field=models.CharField(help_text='주문 ID', max_length=100),
        ),
    ]
