# Generated by Django 5.2.6 on 2025-09-11 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_analyzedstock_alter_tradelog_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='종목코드', max_length=20)),
                ('stock_name', models.CharField(help_text='종목명', max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='보유 수량')),
                ('average_buy_price', models.DecimalField(decimal_places=2, help_text='평균 매수 단가', max_digits=15)),
                ('stop_loss_price', models.DecimalField(decimal_places=2, help_text='손절매 가격', max_digits=15)),
                ('target_price', models.DecimalField(decimal_places=2, help_text='목표(익절) 가격', max_digits=15)),
                ('is_open', models.BooleanField(default=True, help_text='현재 보유 중인 포지션 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='trading.tradingaccount')),
                ('entry_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_entry', to='trading.tradelog')),
            ],
            options={
                'unique_together': {('account', 'symbol', 'is_open')},
            },
        ),
    ]
