# Generated by Django 5.2.6 on 2025-09-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedstock',
            name='is_investable',
            field=models.BooleanField(default=False, help_text='1차 분석(투자가치) 통과 여부'),
        ),
        migrations.AlterField(
            model_name='analyzedstock',
            name='raw_analysis_data',
            field=models.JSONField(blank=True, default=dict, help_text='분석에 사용된 원본 데이터 (재무비율 등)'),
        ),
    ]
