# Generated by Django 5.2.6 on 2025-09-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0005_alter_analyzedstock_is_investable_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tradelog",
            name="strategy",
        ),
        migrations.DeleteModel(
            name="AccountStrategy",
        ),
        migrations.DeleteModel(
            name="Strategy",
        ),
    ]
