# Generated by Django 5.2.6 on 2025-09-11 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0006_remove_tradelog_strategy_delete_accountstrategy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_term_allocation",
                    models.DecimalField(
                        decimal_places=2,
                        default=30.0,
                        help_text="단기 투자 전략에 할당할 자본의 비율(%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "mid_term_allocation",
                    models.DecimalField(
                        decimal_places=2,
                        default=40.0,
                        help_text="중기 투자 전략에 할당할 자본의 비율(%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "long_term_allocation",
                    models.DecimalField(
                        decimal_places=2,
                        default=30.0,
                        help_text="장기 투자 전략에 할당할 자본의 비율(%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI 전략 설정",
                "verbose_name_plural": "AI 전략 설정",
            },
        ),
    ]
