# Generated by Django 5.2.6 on 2025-09-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0008_alter_strategysettings_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="portfolio",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="portfolio",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_open", True)),
                fields=("account", "symbol"),
                name="unique_open_position_per_account",
            ),
        ),
    ]
