# Generated by Django 5.0.7 on 2025-09-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_merge_20240716_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, help_text='The stock symbol (ticker).', max_length=20)),
                ('date', models.DateField(db_index=True, help_text='The date of the price data.')),
                ('open_price', models.DecimalField(decimal_places=2, help_text='Opening price.', max_digits=15)),
                ('high_price', models.DecimalField(decimal_places=2, help_text='Highest price of the day.', max_digits=15)),
                ('low_price', models.DecimalField(decimal_places=2, help_text='Lowest price of the day.', max_digits=15)),
                ('close_price', models.DecimalField(decimal_places=2, help_text='Closing price.', max_digits=15)),
                ('volume', models.BigIntegerField(help_text='Trading volume for the day.')),
            ],
            options={
                'verbose_name': 'Historical Price Data',
                'verbose_name_plural': 'Historical Price Data',
                'ordering': ['-date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]