# Generated by Django 5.2.6 on 2025-09-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0009_alter_portfolio_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalPriceData",
        ),
        migrations.AlterModelOptions(
            name="strategysettings",
            options={"verbose_name": "전략 설정", "verbose_name_plural": "전략 설정"},
        ),
        migrations.RemoveField(
            model_name="strategysettings",
            name="long_term_allocation",
        ),
        migrations.RemoveField(
            model_name="strategysettings",
            name="mid_term_allocation",
        ),
        migrations.RemoveField(
            model_name="strategysettings",
            name="short_term_allocation",
        ),
        migrations.AddField(
            model_name="strategysettings",
            name="dca_base_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=100000.0,
                help_text="우량주 분할매수: 1회당 기본 투자 금액",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="strategysettings",
            name="dca_settings_json",
            field=models.JSONField(
                default=dict, help_text="동적 분할매수 설정 (KOSPI 하락률에 따른 배율)"
            ),
        ),
        migrations.AddField(
            model_name="strategysettings",
            name="max_total_risk",
            field=models.DecimalField(
                decimal_places=3,
                default=0.1,
                help_text="단기 트레이딩: 포트폴리오 최대 총 리스크 비율 (예: 0.1 for 10%)",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="strategysettings",
            name="risk_per_trade",
            field=models.DecimalField(
                decimal_places=3,
                default=0.01,
                help_text="단기 트레이딩: 개별 종목 최대 리스크 비율 (예: 0.01 for 1%)",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="strategysettings",
            name="trading_fee_rate",
            field=models.DecimalField(
                decimal_places=5,
                default=0.00015,
                help_text="매매 수수료 (예: 0.00015 for 0.015%)",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="strategysettings",
            name="trading_tax_rate",
            field=models.DecimalField(
                decimal_places=5,
                default=0.002,
                help_text="증권거래세 (매도 시 적용, 예: 0.0020 for 0.20%)",
                max_digits=6,
            ),
        ),
    ]
